first_school = input("Type a college name: ")
first_adjective = input("Type an adjective ending in -ly: ")
first_food = input("Type of food: ")
first_verb = input("Type verb ending in -ing: ")
second_school = input("Type second college name: ")
second_adjective = input("Type a second adjective ending in -ly: ")
third_adjective = input("Type a third adjective: ")
first_alcohol = input("Type an alcohol: ")
third_school = input("Type third college name: ")
fourth_adjective = input("Type fourth adjective ending in -ly: ")
first_number = input("Enter an integer: ")
second_number = input("Enter second integer: ")
print()
print("They say that in " + first_school)
print("the food is " + first_adjective + " fine")
print("the " + first_food + " jumped off the table")
print("and started " + first_verb + " time")
print()
print("They say that in " + second_school)
print("the coffee is " + second_adjective + " fine")
print("Looks like " + third_adjective + " water")
print("and tastes like " + first_alcohol)
print()
print("They say that in " + third_school)
print("the scholarships are " + fourth_adjective + " fine")
print("they give you " + first_number + " dollars")
print("and take back " + second_number)
